name: Release

on:
  push:
    tags:
      # Semantic versioning tags only (e.g., v1.0.0, v2.1.3)
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install ARM toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
    
    - name: Install CMake and Ninja
      run: |
        sudo apt-get install -y cmake ninja-build
    
    - name: Configure Release build
      run: |
        cmake --preset Release
    
    - name: Build Release firmware
      run: |
        cmake --build --preset Release
    
    - name: Generate binary and hex files
      run: |
        cd build/Release
        arm-none-eabi-objcopy -O binary MIDI2USB-Converter.elf MIDI2USB-Converter.bin
        arm-none-eabi-objcopy -O ihex MIDI2USB-Converter.elf MIDI2USB-Converter.hex
    
    - name: Display firmware info
      run: |
        echo "Firmware size information:"
        arm-none-eabi-size build/Release/MIDI2USB-Converter.elf
        echo ""
        echo "Binary file size:"
        ls -lh build/Release/MIDI2USB-Converter.bin
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        files: |
          build/Release/MIDI2USB-Converter.elf
          build/Release/MIDI2USB-Converter.bin
          build/Release/MIDI2USB-Converter.hex
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}