name: Release

on:
  push:
    tags:
      # Semantic versioning tags only (e.g., v1.0.0, v2.1.3)
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    
    - name: Install ARM toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
    
    - name: Install CMake and Ninja
      run: |
        sudo apt-get install -y cmake ninja-build
    
    - name: Extract version from tag
      id: version
      run: |
        # Extract version from tag (e.g., v1.2.3 -> 1.2.3)
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV

        # Split version into components
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        echo "VERSION_MAJOR=${MAJOR:-1}" >> $GITHUB_ENV
        echo "VERSION_MINOR=${MINOR:-0}" >> $GITHUB_ENV
        echo "VERSION_PATCH=${PATCH:-0}" >> $GITHUB_ENV

        # Create full version string with tag
        echo "VERSION_FULL=MIDI2USB v$VERSION (${GITHUB_SHA::8})" >> $GITHUB_ENV

    - name: Configure Release build
      run: |
        cmake --preset Release \
          -DVERSION_MAJOR=${{ env.VERSION_MAJOR }} \
          -DVERSION_MINOR=${{ env.VERSION_MINOR }} \
          -DVERSION_PATCH=${{ env.VERSION_PATCH }} \
          -DVERSION_STRING="\"${{ env.VERSION_FULL }}\""

    - name: Build Release firmware
      run: |
        cmake --build --preset Release
    
    - name: Generate binary and hex files
      run: |
        cd build/Release
        arm-none-eabi-objcopy -O binary MIDI2USB-Converter.elf MIDI2USB-Converter.bin
        arm-none-eabi-objcopy -O ihex MIDI2USB-Converter.elf MIDI2USB-Converter.hex
    
    - name: Display firmware info
      run: |
        echo "Firmware size information:"
        arm-none-eabi-size build/Release/MIDI2USB-Converter.elf
        echo ""
        echo "Binary file size:"
        ls -lh build/Release/MIDI2USB-Converter.bin
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false
        files: |
          build/Release/MIDI2USB-Converter.elf
          build/Release/MIDI2USB-Converter.bin
          build/Release/MIDI2USB-Converter.hex
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}